### ISSUE TITLE
Further minimize size of the generated AppImages

### ISSUE THREAD

**Issue by probonopd** [niess/linuxdeploy-plugin-python#1] opened 2019-06-06 06:06 UTC
Here is an idea on how to further hand-optimize the size of the generated AppImages. It works by using the Linux kernel at runtime to check which files from the AppDir have been accessed, and deleting all others. What do you think?

```
sudo mount -t tmpfs tmpfs squashfs-root/ -o strictatime,nodiratime 
./Some.AppImage --appimage-extract
touch test
./squashfs-root/AppRun # Run and exercise all parts of the app so that all needed files get accessed
# Kill
find squashfs-root/ -mindepth 3 -anewer test -not -path '*/share/icons/*' -not -path '*/share/applications/*' -not -path '*/share/metainfo/*' 
find squashfs-root/ -mindepth 3 -not -anewer test -not -path '*/share/icons/*' -not -path '*/share/applications/*' -not -path '*/share/metainfo/*' -delete || true
find squashfs-root/ -type d -empty -delete
./squashfs-root/AppRun 
# Does it still run when thinned?
```

What if we need to use a local developer machine to determine the set of needed files but want to generate the thinned AppDir on a build machine? Use a `MANIFEST` file that specifies the wanted files:

```
# Make a MANIFEST (on a local developer machine)
( cd squashfs-root/ ; find . -type f -or -type s | sort | uniq  > ../MANIFEST )

# Delete everything from the AppDir that is not in the MANIFEST
( cd appdir/ ; find . -type f -or -type s | sort | uniq > ../ALLFILES ; diff --new-line-format="" --unchanged-line-format="" ../ALLFILES ../MANIFEST | xargs -r rm )
find appdir/ -type d -empty -delete
```

**Comment by niess** [comment] 2019-06-07 06:54
Hello. Thank you. I'll give it a try :)
I'm currently struggling with Travis, dependencies etc, getting it to build the  Python apps. Having to wait ~5 min between 2 tries doesn't make the debug process very efficient :( It works great on my local PC however :)

**Comment by niess** [comment] 2019-06-08 01:41
Hey @probonopd . I didn't manage to run from the extracted directory following your scheme. I must be missing something. For example, I don't understand why you create a mount point? Isn't it enough to extract the content and point APPDIR, APPIMAGE, and ARGV0 to the corresponding locations? Well it only partially worked for me doing so. In some cases it was segfaulting. So it must not be enough :P

Anyway, I went back to stripping the image by direct inspection. Actually there were test data embedded and other obviously unused things. So now its 2 times smaller: ~22 Mb, which I think is already great considering that the same python3.7 in my system is a 100 Mb, excluding test data etc. as well. The external dependencies detected by linuxdeploy are 7% of the extracted size. So it looks like a fair deal to me in this case :) I mean packaging them to improve the portability.

In principle the size could be reduced even more by keeping only Python's bytecode, i.e. deleting the *.py source files having a *.pyc companion. I'll give it a try. Your systematic strategy of checking which files are accessed would tell :)

@TheAssassin , in comparison, the raw conda based image obtained with linuxdeploy-plugin-conda is 24 MB. It grows to 275 Mb with numpy :( Which surprises me since the PYPI install of numpy is only ~70 MB. Maybe this is due to external dependencies?

**Comment by TheAssassin** [comment] 2019-06-08 12:00
@niess if you can give me two AppImages (or build recipes) I'll have a look.

I would not delete Python source code, the AppImage should remain readable IMO. But that's up to you. You could also create `.pyo` files with optimized bytecode.

linuxdeploy-plugin-conda only deletes what it can safely assume to be unnecessary during runtime, the challenge is not to create as minimal as possible AppImages, users can always optimize a little, too.

**Comment by probonopd** [comment] 2019-06-08 19:50
>  For example, I don't understand why you create a mount point? 

So that we get `strictatime,nodiratime` kernel functionality.

> Isn't it enough to extract the content and point APPDIR, APPIMAGE, and ARGV0 to the corresponding locations?

No, most likely your normal filesystem does not have `strictatime,nodiratime` kernel functionality enabled, and hence access times will not be reported by the kernel, which means too much will be stripped.

> Well it only partially worked for me doing so. In some cases it was segfaulting. So it must not be enough :P

Please try again using the mountpoint. What is segfaulting, and when?

**Comment by niess** [comment] 2019-06-08 19:58
@TheAssassin I just extracted the conda-numpy image. 710 MB out of 810 MB are for the MKL library, i.e. an external dependency indeed, for linear algebra. I attached an archive ([conda-numpy.zip](https://github.com/niess/linuxdeploy-plugin-python/files/3268882/conda-numpy.zip)) with data used to build the image, as:
```
TAG=numpy ./build-appimage.sh
```

Also, trying to compare performances of MKL (anaconda) vs OpenBLAS (PyPi), I noticed that when there is a system install of numpy on the host it takes precedence over the conda-numpy (AppImage) one. This is likely due to Python systematically adding `/usr/local/lib/pythonX.Y/site-packages` to its search path, before the AppImage site-packages. I disabled this with a [sitecustomize.py](https://github.com/niess/linuxdeploy-plugin-python/blob/master/share/sitecustomize.py#L7) script, set by the python plugin for linuxdeploy. Note that 
it is still possible to add it explicitly to PYTHONPATH, if really wanted.

P.S: I didn't see significant differences using [this benchmark](https://gist.github.com/markus-beuckelmann/8bc25531b11158431a5b09a45abd6276). On my PC, using Python 3.7 and numpy 1.16.4, OpenBLAS and MKL have similar performances within 10%, depending on the category, with no overall winner.

**Comment by niess** [comment] 2019-06-08 20:02
Forgot to say, @TheAssassin , I agree with you that for a generic tool its not a good idea to erase the source files etc. The user could still do it afterwards if wanted. Yet, now I have the virus of trying to optimize it out :P So I'll probably give it a go, generating .pyo as you said, and add it as an option if proves to be relevant.

**Comment by niess** [comment] 2019-06-08 20:28
@probonopd I tried again. Its working :) Just I had to manually export APPDIR to squashfs-root before running AppRun. My AppRun is a wrapper using this env variable in order to call the true executable. I have no clue why it was segfaulting yesterday. Probably that was me missing something in my config.

Following your steps (which I still need to take some time to understand :P), the thinned application runs the same :) It is only 3 MB uncompressed (against 90 MB initially). Now the problem is that I only experimented a small part of the application. I noticed that a lot of packages that I didn't import at 1st have been deleted. So I'll have to ensure that at the initial step a complete test of the app is done. For example by running the Python built-in unit test? (that I erased previously) Or simply by importing all packages recursively.

Anyway, thanks for the help! This looks like a promising systematic way to thin the app :)

**Comment by probonopd** [comment] 2019-06-08 20:52
It works by the kernel looking at which files are actually being accessed. So you need to exercise all areas of your application.

**Comment by TheAssassin** [comment] 2019-06-09 12:00
@niess so you're telling that your Python plugin does not bundle dependencies installed on the system (like that MKL lib)? That's why conda is convenient, the conda packages are completely portable and there's a full-blown set of dev tools available in that env, so you can even build stuff from PyPI if needed.

**Comment by niess** [comment] 2019-06-09 23:45
@TheAssassin there is a miss-understanding. I mixed several topics. 

1. I'm trying to bundle dependencies as well. Just I was surprised that conda+numpy AppImage is 275 MB whereas python (source) + numpy (PyPI) AppImage is only 40 MB. The difference is due to conda shipping MKL as backend for linear algebra whereas PyPI ships OpenBlas (its hidden in `site-packages/numpy/.libs`). Both have these dependencies fully included in the AppImage.

2. Currently, if there is a system Python package already installed, the conda-plugin will load the system package instead of the AppImage one (same Python version, e.g. 3.7). This is due to a "feature" (bug?) in the Python init sequence. There is a simple solution to that. I'll try to report this as an `issue` on the conda plugin page. It will be clearer. But right now its too late :(

**Comment by niess** [comment] 2019-06-26 14:07
@probonopd  I'm closing this issue for now. I don't think that I can further reduce the Image size for a generic Python distribution. However, it would be useful to have a separate tool that automatises your idea. Applications relying on Python for the GUI would typically use only a small subset of the standard Python library.

**Closed by niess** 2019-06-26 14:07 UTC
